# Generated by Django 3.2.16 on 2023-02-13 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='constraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('exam_time', models.CharField(default='none', max_length=50)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='5', max_length=10)),
                ('dept', models.CharField(choices=[('ise', 'information science'), ('eee', 'electrical'), ('cse', 'computer science'), ('ece', 'electronics and communication')], default='cse', max_length=3)),
                ('subject', models.CharField(default='none', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('fname', models.CharField(default='none', max_length=50, primary_key=True, serialize=False)),
                ('faculty_id', models.CharField(max_length=4)),
                ('faculty_status', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='y', max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('dept', models.CharField(choices=[('ise', 'information science'), ('eee', 'electrical'), ('cse', 'computer science'), ('ece', 'electronics and communication')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('feedback', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='EXAM TIMETABLE', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('roomno', models.IntegerField(primary_key=True, serialize=False)),
                ('roomcapacity', models.IntegerField()),
                ('room_status', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('rollno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_dept', models.CharField(choices=[('ise', 'information science'), ('eee', 'electrical'), ('cse', 'computer science'), ('ece', 'electronics and communication')], max_length=3)),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
            ],
        ),
        migrations.CreateModel(
            name='tt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedule', models.ImageField(default='null', upload_to='')),
                ('Section', models.CharField(max_length=50, null='False')),
                ('Branch', models.CharField(choices=[('cse', 'CSE'), ('ise', 'ISE'), ('eee', 'EEE'), ('ece', 'ECE')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='seating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_roll', models.CharField(max_length=10)),
                ('last_roll', models.CharField(max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.room')),
            ],
        ),
        migrations.CreateModel(
            name='conduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fna2', models.CharField(max_length=50, null=True)),
                ('ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.exam')),
                ('fna1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.faculty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.room')),
            ],
        ),
    ]
